robot_store/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resource :accounts
  resources :purchases
end

robot_store/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

robot_store/app/models/payment.rb
class Payment < ApplicationRecord
  validates :txid, :value, :included_in_block, presence: true
  validates :txid, uniqueness: true

  belongs_to :user
end

robot_store/app/models/payment_fetcher.rb
class PaymentFetcher
  def self.load!
    processor = PaymentProcessor.new
    # Need to check only users with addresses
    User.where.not(deposit_address: nil).find_each do |user|
      # Load all transactions related to the user address
      Rails.logger.warn("Load transaction for address: #{user.deposit_address}")
      processor.get_address_unspent(user.deposit_address)
      unless processor.body.any?
        next
      end
      # Check each transaction, if it's has any confirmations
      processor.body.each do |tx|
        payment = user.payments.find_by(txid: tx['tx_hash'])
        if payment
          # if any payments exists 
          # and height is not the same therefore
          # transaction was confirmed 
          if payment.included_in_block != tx['height']
            payment.update(included_in_block: tx['height'])
          end
        else
          # add payments if not exists
          user.payments.create(
            txid: tx['tx_hash'],
            value: tx['value'],
            included_in_block: tx['height']
          )
        end
      end
    end
  end
end

robot_store/app/models/payment_processor.rb
require 'httparty'

class PaymentProcessor
  include HTTParty
  base_uri "http://#{RobotStore::Application.secrets.btc_host}:#{RobotStore::Application.secrets.btc_port}"

  def initialize
    @request_id = 0
    @options = {
      headers: { "Content-Type" => "application/json" },
      basic_auth: {
        username: RobotStore::Application.secrets.btc_user,
        password: RobotStore::Application.secrets.btc_password
      }
    }
  end

  # Create a new receiving address,
  # beyond the gap limit of the wallet
  def get_new_address
    request do
      build_params("createnewaddress")
    end
  end

  # Returns the UTXO list of any address
  # https://bitcoin.org/en/glossary/unspent-transaction-output
  def get_address_unspent(address)
    request do
      build_params("getaddressunspent", address)
    end
  end

  def body
    @body["result"]
  end

  def success?
    @success
  end

  private

  def request
    @request_id = @request_id.next
    response = self.class.post(
      "/", 
      @options.merge!(body: yield.to_json)
    )
    @body, @success = response.parsed_response, response.success?
  end
  

  def build_params(method, params = nil)
    {
      id: @request_id,
      method: method,
      params: [params].compact 
    }
  end
end

robot_store/app/models/purchase.rb
class Purchase < ApplicationRecord
  validates :user_id, :robot_id, :value, presence: true
  belongs_to :user
  belongs_to :robot
end

robot_store/app/models/robot.rb
class Robot < ApplicationRecord
  validates :title, :price, :avatar, presence: true
end

robot_store/app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :payments

  has_many :purchases
  has_many :robots, through: :purchases

  def unconfirmed
    # the unconfirmed balance is the sum of unconfirmed transaction values
    payments.where(included_in_block: 0).sum(:value) / 100_000_000.0 # because values in the satoshi 0.00000001 BTC is 1 satoshi
  end

  def balance
    (confirmed - purchases.sum(:value)) / 100_000_000.0
  end

  def confirmed
    # the confirmed balance is the sum of confirmed transaction values
    payments.where('included_in_block > 0').sum(:value) # because values in the satoshi 0.00000001 BTC is 1 satoshi
  end
end

robot_store/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_user.deposit_address
      flash[:success] = "You already have deposit address"
      redirect_to root_path
    else
      payments = PaymentProcessor.new
      payments.get_new_address
      if payments.success?
        current_user.update(deposit_address: payments.body)
        flash[:success] = "Address successfully requested"
        redirect_to root_path
      else
        flash[:error] = "Cant get address for you"
        redirect_to root_path
      end
    end
  end
end

robot_store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

robot_store/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @merch = Robot.all.order(:price)
  end
end

robot_store/app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!
  def index
    @robots = current_user.robots
  end

  def create
    if current_user.confirmed.zero?
      flash[:error] = "You have not enough funds"
      redirect_to root_path
    else
      robot = Robot.find(params[:robot_id])
      if robot.price.to_f < current_user.balance && (current_user.balance - robot.price.to_f) > 0
        current_user.purchases.create(
          robot_id: robot.id,
          value: (robot.price.to_f * 100_000_000).to_i
        )
        flash[:success] = "Cheers! You have new robot!"
        redirect_to purchases_path
      else
        flash[:error] = "You have not enough funds"
        redirect_to root_path
      end
    end
  end
end

robot_store/app/helpers/application_helper.rb
module ApplicationHelper
end

robot_store/app/views/home/index.html.erb
<h1>Robots Store</h1>
<div class='grid'>
  <% @merch.each_slice(3) do |robots| %>
    <div>
      <% robots.each do |r| %>
        <span style='position: absolute;text-align: left'>
          <small><%= r.title %>
            <b><%= signed_in? ? link_to('Buy', purchases_path(robot_id: r.id), method: :post) : link_to('Buy', new_user_session_path) %></b>
          </small> <br/>
        <b><small>Price: <%= number_to_currency(r.price, unit: 'B', precision: 8) %></small></b><br/>
        </span>
        <%= image_tag r.avatar, style: 'background: #737f7f;margin-top: 40px;border: 1px black dotted' %>
      <% end %>
    </div>
  <% end %>
</div>

robot_store/app/views/layouts/_header.erb
<ul>
  <li><%= link_to 'Main', root_path %></li>
  <% if signed_in? %>
    <li>Your balance:<br/>
      <ul>
        <li>
          Confirmed: <b><%= number_to_currency(current_user.balance, unit: 'B', precision: 8) %></b>
        </li>
        <li>
          Unconfirmed: <b><%= number_to_currency(current_user.unconfirmed, unit: 'B', precision: 8) %></b>
        </li>
      </ul>
    </li>
    <% if current_user.deposit_address %>
      <ul>
        <li style='font-style: italic;'>Your deposit address: <b><%= current_user.deposit_address %></b></li>
      </ul>
    <% else %>
      <ul>
        <li style='font-style: italic;'>In order to make a deposit, request an address click <%= link_to 'here', accounts_path, method: :post %>.</li>
      </ul>
    <% end %>
    <% if current_user.robots.any? %>
      <li><%= link_to('Your robots', purchases_path) %></li>
    <% end %>
    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'Login', new_user_session_path %></li>
    <li><%= link_to 'Register', new_user_registration_path %></li>
  <% end %>
</ul>

robot_store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Robots Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
      <%= render 'layouts/header' %>
      <div style="text-align: center">
        <div style="text-align: center;color: green">
          <% if flash[:success] %>
            <%= flash[:success] %>
          <% end %>
        </div>
        <div style="text-align: center;color: red">
          <% if flash[:error] %>
            <%= flash[:error] %>
          <% end %>
        </div>
        <%= yield %>
      </div>
  </body>
</html>

robot_store/app/views/purchases/index.html.erb
<h1>Your robots</h1>
<div class='grid'>
  <% @robots.each_slice(3) do |robots| %>
    <div>
      <% robots.each do |r| %>
        <span style='position: absolute;text-align: left'>
          <small><%= r.title %> </small><br />
        <b><small>Price: <%= number_to_currency(r.price, unit: 'B', precision: 8) %></small></b><br/>
        </span>
        <%= image_tag r.avatar, style: 'background: #737f7f;margin-top: 40px;border: 1px black dotted' %>
      <% end %>
    </div>
  <% end %>
</div>